# -*- coding: utf-8 -*-
"""redsox.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4ae078x4_Dt_tEKl7Hgdh2VXxiKUjGs
"""

pip install tweepy textblob

import tweepy
from textblob import TextBlob

# Twitter API credentials
API_KEY = 'goKhFoGQ5gqHKjtNpuMEiobyU'
API_SECRET_KEY = 'kA58d5PqwSh0bddyGWRED3yXHvJDD1cHNZoWlR2geWY573gfSM'
ACCESS_TOKEN = '2971337289-wvyG2J9MhVntXdBn6aGSDdzvwU8MUoOSoTfjRyC'
ACCESS_TOKEN_SECRET = 'gudZ7OQhMvKMI6PWCa7qxiTm7iJabjhD7p2vDW2aawj7v'

# Set up Tweepy API client
auth = tweepy.OAuthHandler(API_KEY, API_SECRET_KEY)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

# Function to perform sentiment analysis on a tweet
def analyze_sentiment(tweet_text):
    blob = TextBlob(tweet_text)
    polarity = blob.sentiment.polarity
    return polarity

# Function to scrape tweets related to the Boston Red Sox
def scrape_tweets():
    search_query = "Boston Red Sox"
    tweet_count = 100

    # Collect tweets
    tweets = tweepy.Cursor(api.search_tweets, q=search_query, lang='en').items(tweet_count)

    # Perform sentiment analysis on each tweet
    positive_count = 0
    negative_count = 0
    neutral_count = 0

    for tweet in tweets:
        tweet_text = tweet.text
        sentiment_score = analyze_sentiment(tweet_text)

        if sentiment_score > 0:
            positive_count += 1
        elif sentiment_score < 0:
            negative_count += 1
        else:
            neutral_count += 1

    total_count = positive_count + negative_count + neutral_count

    # Calculate sentiment percentages
    positive_percentage = (positive_count / total_count) * 100
    negative_percentage = (negative_count / total_count) * 100
    neutral_percentage = (neutral_count / total_count) * 100

    print(f"Positive Sentiment: {positive_percentage:.2f}%")
    print(f"Negative Sentiment: {negative_percentage:.2f}%")
    print(f"Neutral Sentiment: {neutral_percentage:.2f}%")

if __name__ == "__main__":
    scrape_tweets()







